routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Route::group([
    'middleware' => 'guest',
    'prefix' => 'login'
], function () {
    Route::get('/', 'LoginController@showLoginForm')->name('login');
    Route::post('/', 'LoginController@login');
});

Route::post('/logout', 'LoginController@logout')
    ->middleware('auth')
    ->name('logout');

/*
|--------------------------------------------------------------------------
| Special
|--------------------------------------------------------------------------
|
*/

Route::get('/result-{session_id}', 'ResultController@index')->name('result');

/*
|--------------------------------------------------------------------------
| Web Routes Continue
|--------------------------------------------------------------------------
|
*/

Route::get('/', 'IndexController@index');

app/Models/Examinee.php
<?php

namespace App\Models;

use App\Business\Data\Fields\FieldAccess;
use App\Business\Data\Fields\JsonField;
use Illuminate\Database\Eloquent\Model;

class Examinee extends Model
{
    use FieldAccess, JsonField;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'uid',
        'data',
        'ga',
    ];

    /**
     * The primary key for the model.
     *
     * @var string
     */
    protected $primaryKey = 'uid';

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * Session - 1:m
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function sessions()
    {
        return $this->hasMany(Session::class, 'examinee_uid');
    }

    /**
     * Возвращает короткую версию уникального идентификатора
     *
     * @return string
     */
    public function getShortUidAttribute()
    {
        $s = $this->getFieldValue('uid');

        return mb_substr($s, 0, min(8, mb_strlen($s)));
    }

    /**
     * Возвращает данные в виде JSON-а
     *
     * @return array
     */
    public function getDataAttribute()
    {
        return $this->getJsonValue('data');
    }

    /**
     * Задает данные, как JSON
     *
     * @param  array  $value
     * @return void
     */
    public function setDataAttribute(array $value)
    {
        $this->setJsonValue('data', $value);
    }

    /**
     * Преобразует определенное поле из набора данных
     *
     * @param  string  &$field
     * @param  &$value
     */
    public function mutateDataField(string &$field, &$value)
    {
        // functions

        $stamp_v = function ($value) {
            return date('Y-m-d H:i:s', $value);
        };

        // config

        $arr = [

            'ip' => [
                'k' => 'IP-адрес',
                'v' => null,
            ],

            'stamp' => [
                'k' => 'Дата/Время',
                'v' => $stamp_v,
            ],

        ];

        // mutation

        if (array_key_exists($field, $arr)) {
            $info = $arr[$field];

            $field = $info['k'];
            $value = is_callable($info['v']) ? call_user_func($info['v'], $value) : $value;
        }
    }
}

app/Models/Session.php
<?php

namespace App\Models;

use App\Business\Data\Examining\ExamineResultAccessible;
use App\Business\Data\Fields\FieldAccess;
use App\Business\Data\Fields\FileField;
use App\Support\HasTrueTranslator;
use Illuminate\Database\Eloquent\Model;
use Imagick;
use ImagickDraw;
use ImagickPixel;

class Session extends Model implements ExamineResultAccessible
{
    use FieldAccess, FileField, HasTrueTranslator;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'sex',
        'age',
        'answers',
        'score',
        'finished_at',
        'examinee_uid',
    ];

    /**
     * Examinee - 1:m
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function examinee()
    {
        return $this->belongsTo(Examinee::class, 'examinee_uid');
    }

    /**
     * Answer - 1:m
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function answerModels()
    {
        return $this->hasMany(Answer::class, 'session_id');
    }

    /**
     * Возвращает пол в удобочитаемом виде
     *
     * @return string
     */
    public function getHumanSexAttribute()
    {
        $s = $this->getFieldValue('sex');
        $arr = [
            'm' => 'Мужской',
            'f' => 'Женский',
        ];

        return array_key_exists($s, $arr) ? $arr[$s] : 'Неизвестен';
    }

    /**
     * Возвращает возраст в удобочитаемом виде
     *
     * @return string
     */
    public function getHumanAgeAttribute()
    {
        $s = $this->getFieldValue('age');
        $arr = [];

        if (starts_with($s, '_')) {
            $arr[] = '<';
            $arr[] = mb_substr($s, 1);
        } elseif (ends_with($s, '_')) {
            $arr[] = '>';
            $arr[] = mb_substr($s, 0, -1);
        } elseif (mb_strpos($s, '-') !== false) {
            $arr[] = str_replace('-', ' - ', $s);
        } else {
            $arr[] = empty($s) ? 'Неизвестно' : $s;
        }

        return implode(' ', $arr);
    }

    /**
     * Возвращает название для картинки с результатом тестирования
     *
     * @param  string  $suffix
     * @return string
     */
    protected function getResultImageName(string $suffix)
    {
        return $this->id . $suffix . '.png';
    }

    /**
     * Возвращает ссылку на картинку с результатом тестирования
     *
     * @return string
     */
    public function getResultImageAttribute()
    {
        return $this->getFileStorage()->url(
            $this->getResultImageName('')
        );
    }

    /**
     * Возвращает ссылку на картинку с результатом тестирования для соц.сети "одноклассники"
     *
     * @return string
     */
    public function getResultImageOkAttribute()
    {
        return $this->getFileStorage()->url(
            $this->getResultImageName('_ok')
        );
    }

    /**
     * Возвращает результат тестирования
     *
     * @return int
     */
    public function getExamineResult()
    {
        return $this->score;
    }

    /**
     * Генерирует картинку с результатом тестирования
     *
     * @param  string  $target
     * @return void
     */
    public function generateResultImage(string $target)
    {
        $suffix = empty($target) ? '' : '_' . $target;
        $path = $this->getFileStorage()->path(
            $this->getResultImageName($suffix)
        );

        $result = $this->getExamineResult();
        $source = public_path('assets/result_' . $this->sex . $suffix . '.png');

        if (!file_exists($source)) {
            $source = public_path('assets/result_m' . $suffix . '.png');
        }

        $img = new Imagick($source);
        $drw = new ImagickDraw();
        $pxl = new ImagickPixel('white');

        $x = 120.0;
        $y = 105.0;

        $drw->setFont(base_path('resources/assets/fonts/MyriadPro-Regular.ttf'));
        $drw->setFontSize(56);
        $drw->setStrokeColor($pxl);
        $drw->setFillColor($pxl);
        $img->annotateImage($drw, $x, $y, 0, $result);

        $size = $img->queryFontMetrics($drw, $result);
        $x += 2.5;
        $y += ($size['textHeight'] / 4.0);

        $drw = clone $drw;
        $drw->setFontSize(16);
        $img->annotateImage($drw, $x, $y, 0, ' час' . word_end_choice($result, '', 'а', 'ов'));

        $img->writeImage($path);
        chmod($path, 0777);
    }

    /**
     * Возвращает тексты результата тестирования
     *
     * @return array
     */
    public function getExamineResultTexts()
    {
        // text A

        $arr = [
            [0, 4],
            [5, 8],
            [9, 12],
            [13, 16],
            [17, 20],
            [21, 24],
        ];

        $a = [];

        foreach ($arr as $item) {
            for ($i = $item[0]; $i <= $item[1]; $i++) {
                $key = 'sessions.results.a.' . $item[0] . '-' . $item[1];

                if ($this->trueTranslator()->hasTranslation($key)) {
                    $a[$i] = $this->trueTranslator()->translate($key);
                }
            }
        }

        // result

        $result = $this->getExamineResult();
        $arr = [];

        if (array_key_exists($result, $a)) {
            $a = explode('|', $a[$result]);

            $arr['a'] = count($a) > 1 ? [
                'title' => $a[0],
                'text' => $a[1],
            ] : [
                'title' => '',
                'text' => $a[0],
            ];
        } else {
            $arr['a'] = [
                'title' => '',
                'text' => '',
            ];
        }

        $b = 'sessions.results.b.' . $this->sex . '.' . $this->age;
        $arr['b'] = $this->trueTranslator()->hasTranslation($b) ? $this->trueTranslator()->translate($b) : '';

        return $arr;
    }
}

app/Http/Controllers/Admin/SessionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Repositories\ExamineeRepository;
use App\Models\Repositories\SessionRepository;
use Illuminate\Http\Request;

class SessionController extends Controller
{
    /**
     * Репозиторий сессий
     *
     * @var \App\Models\Repositories\SessionRepository
     */
    private $sessions;

    /**
     * Создает новый экземпляр контроллера
     *
     * @param  \App\Models\Repositories\SessionRepository  $sessions
     */
    public function __construct(SessionRepository $sessions)
    {
        $this->breadcrumb()->append(route('admin.session'), 'Сессии');
        $this->currentMenu()->addLeft('session');

        $this->sessions = $sessions;
    }

    /**
     * Возвращает репозиторий сессий
     *
     * @return \App\Models\Repositories\SessionRepository
     */
    protected function sessions()
    {
        return $this->sessions;
    }

    /**
     * Список сессий
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $sessions = $this->sessions()->all($request);

        if ($request->has('uid')) {
            /** @var  \App\Models\Repositories\ExamineeRepository  $examinees */
            $examinees = app()->make(ExamineeRepository::class);

            $examinee = $examinees->one($request->input('uid'));
            $this->breadcrumb()->append(
                route('admin.session', ['uid' => $examinee->uid]),
                'Сес.Исп: ' . $examinee->short_uid
            );

            $sessions->appends('uid', $examinee->uid);
        }

        return view('routes.admin.session.index', $this->fillViewData([
            'sessions' => $sessions,
        ]));
    }

    /**
     * Просмотр сессии
     *
     * @param  string  $uid
     * @return \Illuminate\Http\Response
     */
    public function view(string $uid)
    {
        $session = $this->sessions()->one($uid);
        $this->breadcrumb()->append(route('admin.session.view', $session->id), '№' . $session->id);

        return view('routes.admin.session.view', $this->fillViewData([
            'session' => $session,
        ]));
    }
}

resources/views/routes/admin/session/index.blade.php
@extends('layouts.admin')

@section('content')
    <?php /** @var  \Illuminate\Pagination\LengthAwarePaginator  $sessions */ ?>
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <table class="table table-responsive">
                    <thead>
                    <tr>
                        <th>№</th>
                        <th>Пол</th>
                        <th>Возраст</th>
                        <th>Отвечено</th>
                        <th>Баллы</th>
                        <th>Время</th>
                        <th>Превью</th>
                        <th>Испытуемый</th>
                        <th>Действия</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($sessions as $session)
                        <?php /** @var  \App\Models\Session  $session */ ?>
                            <tr>
                                <td>{{ $session->id }}</td>
                                <td>{{ $session->human_sex }}</td>
                                <td>{{ $session->human_age }}</td>
                                <td>{{ $session->answers }}</td>
                                <td>{{ $session->score }}</td>
                                <td>
                                    {{ $session->created_at }}
                                    @if($session->finished_at)
                                        <br>{{ $session->finished_at }}
                                    @endif
                                </td>
                                <td>
                                    @if($session->finished_at)
                                        <div class="box-cont ann">
                                            <img src="{{ $session->result_image }}">
                                        </div>
                                    @else
                                        <i>Нет</i>
                                    @endif
                                </td>
                                <td>
                                    <a class="btn btn-link" href="{{ route('admin.examinee.view', $session->examinee->uid) }}">
                                        {{ $session->examinee->short_uid }}
                                        <i class="fa fa-external-link"></i>
                                    </a>
                                </td>
                                <td>
                                    <a
                                            href="{{ route('admin.session.view', $session->id) }}"
                                            class="btn btn-inverse"
                                            title="Просмотр"
                                    >
                                        <i class="fa fa-search"></i>
                                    </a>
                                </td>
                            </tr>
                        @empty
                            <tr><td colspan="9" class="text-muted text-center">Пусто</td></tr>
                        @endforelse
                    </tbody>
                </table>
                {!! $sessions->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/routes/admin/session/view.blade.php
@extends('layouts.admin')

@section('content')
    <?php /** @var  \App\Models\Session  $session */ ?>
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                @if(!$session->finished_at)
                    <div class="alert alert-warning">
                        Сессия не была завершена
                    </div>
                @endif
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="id">№</label>
                        <input
                                id="id"
                                type="text"
                                class="form-control"
                                value="{{ $session->id }}"
                                readonly
                        >
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="sex">Пол</label>
                        <input
                                id="sex"
                                type="text"
                                class="form-control"
                                value="{{ $session->human_sex }}"
                                readonly
                        >
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="age">Возраст</label>
                        <input
                                id="age"
                                type="text"
                                class="form-control"
                                value="{{ $session->human_age }}"
                                readonly
                        >
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="answers">Отвечено</label>
                        <input
                                id="answers"
                                type="text"
                                class="form-control"
                                value="{{ $session->answers }}"
                                readonly
                        >
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="score">Баллы</label>
                        <input
                                id="score"
                                type="text"
                                class="form-control"
                                value="{{ $session->score }}"
                                readonly
                        >
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="finished_at">Начато</label>
                        <input
                                id="finished_at"
                                type="text"
                                class="form-control"
                                value="{{ $session->created_at }}"
                                readonly
                        >
                    </div>
                </div>
                @if($session->finished_at)
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="finished_at">Завершено</label>
                            <input
                                    id="finished_at"
                                    type="text"
                                    class="form-control"
                                    value="{{ $session->finished_at }}"
                                    readonly
                            >
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Результат</label>
                            <div class="box-cont ann m-b-10">
                                <img src="{{ $session->result_image }}">
                            </div>
                            <div class="box-cont ann m-b-10">
                                <img src="{{ $session->result_image_ok }}">
                            </div>
                            @php($texts = $session->getExamineResultTexts())
                            <textarea
                                    class="form-control m-b-10"
                                    readonly
                            >{!! $texts['a']['title'] . "\n\n" . $texts['a']['text'] !!}</textarea>
                            <textarea
                                    class="form-control"
                                    readonly
                            >{!! $texts['b'] !!}</textarea>
                        </div>
                    </div>
                @endif
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Испытуемый</label>
                        <div class="form-control">
                            <a href="{{ route('admin.examinee.view', $session->examinee->uid) }}">
                                {{ $session->examinee->short_uid }}
                            </a>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
@endsection